export interface espnProTeamSchedule {
  display: boolean;
  settings: espnScheduleSettings;
}

export interface espnScheduleSettings {
  allowedReadPercentage: number;

  allowedWritePercentage: number;

  communcationGated: boolean;

  defaultDraftPosition: number;

  draftLobbyMinimumLeagueCount: number;

  gameNotificationSettings: espnGameNotificationSettings;

  gated: boolean;

  playerOwnershipSettings: espnPlayerOwnershipSettings;

  proTeams: object;

  readOnly: boolean;

  statIdToOverridePosition: {
    [key: string]: number;
  };

  teamActivityEnabled: boolean;

  typeNames: espnTypes;
}

export interface espnPlayerOwnershipSettings {
  firstGameDate: number;
  lastGameDate: number;

  startDate: number;
}

export interface espnProTeam {
  abbrev: string;
  byeWeek: number;
  id: number;
  location: string;

  proGamesByScoringPeriod: {
    "1": espnProGame;
    "2": espnProGame;
    "3": espnProGame;
    "4": espnProGame;
    "5": espnProGame;
    "6": espnProGame;
    "7": espnProGame;
    "8": espnProGame;
    "9": espnProGame;
    "10": espnProGame;
    "11": espnProGame;
    "12": espnProGame;
    "13": espnProGame;
    "14": espnProGame;
    "15": espnProGame;
    "16": espnProGame;
    "17": espnProGame;
  };
}

export interface espnProGame {
  awayProTeamId: number;
  date: number;
  homeProTeamId: number;

  id: number;

  scoringPeriodId: number;

  startTimeTBD: boolean;

  statsOfficial: boolean;

  validForLocking: boolean;
}
export interface espnGameNotificationSettings {
  availabilityNotificationsEnabled: boolean;

  draftNotificationsEnabled: boolean;

  injuryNotificationsEnabled: boolean;

  lineupNotificationsEnabled: boolean;

  positionElegibilityNotificationsEnabled: boolean;

  rosterNewsNotificationsEnabled: boolean;

  startBenchNotificationsEnabled: boolean;

  tradeNotificationsEnabled: boolean;
}

export interface espnTypes {
  acquisitionTypes: ["FREEAGENCY", "WAIVERS_TRADITIONAL", "WAIVERS_CONTINUOUS"];
  draftOrderTypes: ["MANUAL", "DRAFT_START"];
  draftTypes: ["OFFLINE", "SNAKE", "AUTOPICK", "SNAIL", "AUCTION"];
  executionTypes: ["EXECUTE", "CANCEL", "PROCESS"];
  injuryStatusTypes: [
    "ACTIVE",
    "PROBABLE",
    "QUESTIONABLE",
    "DOUBTFUL",
    "OUT",
    "INJURY_RESERVE",
    "DAY_TO_DAY",
    "FIFTEEN_DAY_DL",
    "SIXTY_DAY_DL",
    "SEVEN_DAY_DL",
    "TEN_DAY_DL",
    "BEREAVEMENT",
    "PATERNITY",
    "SUSPENSION"
  ];
  inviteTypes: [
    "EMAIL",
    "FACEBOOK",
    "TWITTER",
    "TEXT_MESSAGE",
    "LEAGUE_DIRECTORY",
    "TRANSITION",
    "LEAGUE_CREATION",
    "LIVE_DRAFT_LOBBY",
    "EMAIL_NONTARGETED",
    "COPY_TO_CLIPBOARD",
    "CLONE_LEAGUE"
  ];
  keeperOrderTypes: ["TRADITIONAL", "END_OF_DRAFT", "SELECTED_ROUND"];
  leagueSubTypes: ["NONE", "DRAFT_LOBBY", "MOCKDRAFT_LOBBY"];
  locktimeTypes: [
    "INDIVIDUAL_GAME",
    "FIRSTGAME_SCORINGPERIOD",
    "INDIVIDUAL_FIRSTGAME_WEEKLY",
    "FIRSTGAME_WEEKLY"
  ];
  logoTypes: ["VECTOR", "CUSTOM", "CUSTOM_VALID"];
  matchupTieRuleTypes: [
    "NONE",
    "HOME_TEAM_WINS",
    "SLOT_POINTS",
    "STAT_POINTS",
    "HIGHEST_PLAYOFF_SEED"
  ];
  messageTypes: [
    "CUSTOM",
    "ACQUISITION_SETTINGS_LIMIT_CHANGE",
    "ACQUISITION_SETTINGS_MATCHUP_LIMITS_CHANGE",
    "ACQUISITION_SETTINGS_MIN_BID_CHANGE",
    "ACQUISITION_SETTINGS_TYPE_CHANGE",
    "ACQUISITION_SETTINGS_WAIVER_HOURS_CHANGE",
    "DIVISION_ADD",
    "DIVISION_MODIFY",
    "DIVISION_REMOVE",
    "DIVISIONS_UPDATE",
    "DRAFT_SETTINGS_CURRENT_KEEPER_CHANGE",
    "DRAFT_SETTINGS_CURRENT_KEEPER_DATE_CHANGE",
    "DRAFT_SETTINGS_DATE_CHANGE",
    "DRAFT_SETTINGS_FUTURE_KEEPER_CHANGE",
    "DRAFT_SETTINGS_FUTURE_KEEPER_DATE_CHANGE",
    "DRAFT_SETTINGS_ORDER_CHANGE",
    "DRAFT_SETTINGS_ORDERTYPE_CHANGE",
    "DRAFT_SETTINGS_TIME_PER_SELECTION_CHANGE",
    "DRAFT_SETTINGS_TRADING_CHANGE",
    "DRAFT_SETTINGS_TYPE_CHANGE",
    "DRAFT_STATUS_DRAFT_COMPLETE",
    "DRAFT_STATUS_IN_PROGRESS_CHANGE",
    "DRAFT_STATUS_RESET",
    "FINANCE_SETTINGS_FEE_CHANGE",
    "INVITE",
    "LEAGUE_CREATE",
    "LEAGUE_DELETE",
    "LEAGUE_UNDELETE",
    "MEMBER_ADD_LM",
    "MEMBER_LEAVE",
    "MEMBER_REMOVE_LM",
    "NOTIFICATION_SETTING_TOGGLE",
    "ROSTER_SETTINGS_LINEUP_LOCKTIME_CHANGE",
    "ROSTER_SETTINGS_LOCKTIME_CHANGE",
    "ROSTER_SETTINGS_POSITION_CHANGE",
    "ROSTER_SETTINGS_SLOT_STATLIMIT_CHANGE",
    "ROSTER_SETTINGS_SLOTCOUNT_CHANGE",
    "ROSTER_SETTINGS_IS_USING_UNDROPPABLES",
    "ROSTER_SETTINGS_UNIVERSE_CHANGE",
    "SCHEDULE_MODIFY",
    "SCHEDULE_RESET",
    "SCHEDULE_SETTINGS_PLAYOFF_MATCHUP_LENGTH_CHANGE",
    "SCHEDULE_SETTINGS_PLAYOFF_TEAM_COUNT_CHANGE",
    "SCHEDULE_SETTINGS_PLAYOFF_TIE_RULE_CHANGE",
    "SCHEDULE_SETTINGS_REG_MATCHUP_PERIOD_COUNT_CHANGE",
    "SCORING_SETTING_HOME_TEAM_BONUS_CHANGE",
    "SCORING_SETTING_ITEM_ADD",
    "SCORING_SETTING_ITEM_CHANGE",
    "SCORING_SETTING_ITEM_MODIFY",
    "SCORING_SETTING_ITEM_REMOVE",
    "SCORING_SETTING_TIE_RULE_CHANGE",
    "SCORING_SETTING_TYPE_CHANGE",
    "SETTINGS_CUSTOMIZABLE_CHANGE",
    "SETTINGS_LEAGUE_TYPE_CHANGE",
    "SETTINGS_MAKE_PRIVATE",
    "SETTINGS_MAKE_PUBLIC",
    "SETTINGS_MOTTO_CHANGE",
    "SETTINGS_NAME_CHANGE",
    "SETTINGS_PUBLIC_CHANGE",
    "SETTINGS_RESTRICTION_CHANGE",
    "SETTINGS_SIZE_CHANGE",
    "STATUS_ACTIVATE",
    "STATUS_FIRST_SCORING_PERIOD_CHANGE",
    "TEAM_ABBREV_CHANGE",
    "TEAM_DIVISION_CHANGE",
    "TEAM_NAME_CHANGE",
    "TEAM_OWNER_DELETE",
    "TEAM_OWNER_JOIN",
    "TEAM_TRAN_COUNTER_CHANGE",
    "TEAM_UPDATE",
    "TEAM_WAIVER_ORDER_CHANGE",
    "TEAMS_ADD",
    "TEAMS_JOINED_COUNT_CHANGE",
    "TEAMS_REMOVE",
    "TRADE_SETTINGS",
    "TRADE_SETTINGS_DEADLINE_CHANGE",
    "TRADE_SETTINGS_LIMIT_CHANGE",
    "TRADE_SETTINGS_REVISION_HOURS_CHANGE",
    "TRADE_SETTINGS_VOTES_REQ_CHANGE",
    "TRANSACTION_FREEAGENT_ADD",
    "TRANSACTION_FREEAGENT_DROP",
    "TRANSACTION_WAIVER_ADD",
    "TRANSACTION_WAIVER_DROP",
    "TRANSACTION_TRADE_ACCEPT",
    "TRANSACTION_TRADE_DECLINE",
    "TRANSACTION_TRADE_PROPOSAL",
    "TRANSACTION_TRADE_UPHOLD",
    "TRANSACTION_TRADE_VETO",
    "TRANSACTION_TRADE_PROCESSED",
    "TRANSACTION_ROSTER_LINEUP",
    "TRANSACTION_DRAFT",
    "TRANSACTION_DRAFT_TRADE",
    "TRANSACTION_FAILED_POSITIONLIMIT",
    "TRANSACTION_FAILED_TRADELOCK",
    "TRANSACTION_FAILED_NOTCLEAREDWAIVERS",
    "TRANSACTION_FAILED_ROSTERLOCK",
    "TRANSACTION_FAILED_LINEUPLOCK",
    "TRANSACTION_FAILED_TRADELIMIT",
    "TRANSACTION_FAILED_ACQUISITIONLIMIT",
    "TRANSACTION_FAILED_SLOTLIMIT",
    "TRANSACTION_FAILED_INELIGIBLESLOT",
    "TRANSACTION_FAILED_IRSLOT",
    "TRANSACTION_FAILED_ROSTERLIMIT",
    "TRANSACTION_FAILED_INVALIDPLAYERSOURCE",
    "TRANSACTION_FAILED_TRANSVALIDATIONFAILED",
    "TRANSACTION_FAILED_NOPERMISSION",
    "TRANSACTION_FAILED_INVALIDROSTER",
    "TRANSACTION_FAILED_CANCELTRANSACTION",
    "TRANSACTION_FAILED_CANCELACCEPTEDTRADE",
    "TRANSACTION_FAILED_UNDROPPABLEPLAYER",
    "TRANSACTION_FAILED_BADUNIVERSE",
    "TRANSACTION_FAILED_PLAYERALREADYDROPPED",
    "TRANSACTION_FAILED_TRADEPLAYERTOIR",
    "TRANSACTION_FAILED_DROPRESERVEDPLAYER",
    "TRANSACTION_FAILED_MATCHUPACQUISITIONLIMIT",
    "TRANSACTION_FAILED_AUCTIONBUDGETEXCEEDED",
    "TRANSACTION_FAILED_PLAYERNOTONROSTER",
    "TRANSACTION_FAILED_MINIMUMBID",
    "TRANSACTION_FAILED_INVALID_FORMAT",
    "SCHEDULE_SETTINGS_PLAYOFF_SEEDING_RULE_CHANGE",
    "ACQUISITION_SETTINGS_WAIVER_ORDER_RESET_ENABLED",
    "ACQUISITION_SETTINGS_WAIVER_ORDER_RESET_DISABLED",
    "ROSTER_SETTINGS_NOT_USING_UNDROPPABLES",
    "STATUS_COMPLETE_LEAGUE_SETUP",
    "TEAM_OWNER_LEAVE",
    "TRANSACTION_TRADE_ACCEPT_TRADE",
    "TRANSACTION_TRADE_ACCEPT_DROP",
    "TRANSACTION_TRADE_ACCEPT_DRAFT_TRADE",
    "TRANSACTION_TRADE_DECLINE_TRADE",
    "TRANSACTION_TRADE_DECLINE_DROP",
    "TRANSACTION_TRADE_DECLINE_DRAFT_TRADE",
    "TRANSACTION_TRADE_PROPOSAL_TRADE",
    "TRANSACTION_TRADE_PROPOSAL_DROP",
    "TRANSACTION_TRADE_PROPOSAL_DRAFT_TRADE",
    "TRANSACTION_TRADE_UPHOLD_TRADE",
    "TRANSACTION_TRADE_UPHOLD_DROP",
    "TRANSACTION_TRADE_UPHOLD_DRAFT_TRADE",
    "TRANSACTION_TRADE_VETO_TRADE",
    "TRANSACTION_TRADE_VETO_DROP",
    "TRANSACTION_TRADE_VETO_DRAFT_TRADE",
    "TRANSACTION_ROSTER_DROP",
    "TRANSACTION_TRADE_VETO_LM",
    "TRANSACTION_TRADE_VETO_LM_TRADE",
    "TRANSACTION_TRADE_VETO_LM_DROP",
    "TRANSACTION_TRADE_VETO_LM_DRAFT_TRADE",
    "TRANSACTION_TRADE_PROCESSED_TRADE",
    "TRANSACTION_TRADE_PROCESSED_DROP",
    "TRANSACTION_TRADE_PROCESSED_DRAFT_TRADE",
    "SCHEDULE_MATCHUP_ADJUSTMENT_CHANGE"
  ];
  moveTypes: [
    "NONE",
    "LINEUP",
    "ADD",
    "DROP",
    "TRADE",
    "DRAFT",
    "UNDRAFT",
    "DRAFT_TRADE"
  ];
  notificationTypes: [
    "TEAM_PLAYER_INJURY",
    "TEAM_PLAYER_AVAILABILITY",
    "TEAM_PLAYER_STARTBENCH",
    "TEAM_PLAYER_NEWS",
    "TEAM_TRADE_OFFER",
    "TEAM_LINEUP",
    "DRAFT",
    "DIRECT_CHAT",
    "TEAM_DAILY_REPORT"
  ];
  periodTypes: ["TOTAL_SEASON", "SCORING_PERIOD", "WEEKLY"];
  playerOwnershipActivityLevels: [
    "ACTIVE_LAST_DAY",
    "ACTIVE_LAST_7_DAYS",
    "ACTIVE_LAST_15_DAYS"
  ];
  playerStatusTypes: ["FREEAGENT", "ONTEAM", "WAIVERS"];
  playoffTierTypes: [
    "WINNERS_BRACKET",
    "WINNERS_CONSOLATION_LADDER",
    "LOSERS_CONSOLATION_LADDER",
    "NONE"
  ];
  pollTypes: ["VOTE_PER_TEAM", "VOTE_PER_OWNER"];
  rankTypes: ["STANDARD", "PPR"];
  recordSeedingRuleTypes: [
    "UNKNOWN",
    "H2H_RECORD",
    "TOTAL_POINTS_SCORED",
    "INTRA_DIVISION_RECORD",
    "TOTAL_POINTS_AGAINST",
    "RAW_STAT"
  ];
  restrictionTypes: [
    "NONE",
    "CHAMPION",
    "INSIDER",
    "ESPN",
    "TEST_LEAGUE",
    "LOAD_TEST"
  ];
  resultTypes: ["WIN", "LOSS", "TIE", "NONE"];
  rosterInjuryStatusTypes: ["NORMAL", "FUTURE_FROM_IR", "FUTURE_TO_IR"];
  rosterStatusTypes: ["NORMAL", "FUTURE_ADD", "FUTURE_DROP", "TRADE_RESERVED"];
  scoringTypes: [
    "ROTO",
    "H2H_POINTS",
    "H2H_CATEGORY",
    "H2H_MOST_CATEGORIES",
    "TOTAL_SEASON_POINTS"
  ];
  topicTypes: [
    "NOTE",
    "POLL",
    "MSG_BOARD",
    "CHAT",
    "EMAIL",
    "OTHER",
    "ACTIVITY_TRANSACTIONS",
    "ACTIVITY_SETTINGS",
    "ACTIVITY_STATUS",
    "ACTIVITY_SCHEDULE",
    "MSG_BOARD_GROUP",
    "MSG_BOARD_MATCHUP",
    "REMINDER_ACTIVATE",
    "REMINDER_SCHEDULE"
  ];
  tradeBlockStatusTypes: ["NORMAL", "ON_THE_BLOCK", "UNTOUCHABLE"];
  transactionStatusTypes: [
    "FAILED_UNKNOWN",
    "PENDING",
    "EXECUTED",
    "CANCELED",
    "FAILED_POSITIONLIMIT",
    "FAILED_TRADELOCK",
    "FAILED_NOTCLEAREDWAIVERS",
    "FAILED_ROSTERLOCK",
    "FAILED_LINEUPLOCK",
    "FAILED_TRADELIMIT",
    "FAILED_ACQUISITIONLIMIT",
    "FAILED_SLOTLIMIT",
    "FAILED_INELIGIBLESLOT",
    "FAILED_IRSLOT",
    "FAILED_ROSTERLIMIT",
    "FAILED_INVALIDPLAYERSOURCE",
    "FAILED_TRANSVALIDATIONFAILED",
    "FAILED_NOPERMISSION",
    "FAILED_INVALIDROSTER",
    "FAILED_CANCELTRANSACTION",
    "FAILED_CANCELACCEPTEDTRADE",
    "FAILED_UNDROPPABLEPLAYER",
    "FAILED_BADUNIVERSE",
    "FAILED_PLAYERALREADYDROPPED",
    "FAILED_TRADEPLAYERTOIR",
    "FAILED_DROPRESERVEDPLAYER",
    "FAILED_MATCHUPACQUISITIONLIMIT",
    "FAILED_AUCTIONBUDGETEXCEEDED",
    "FAILED_PLAYERNOTONROSTER",
    "FAILED_MINIMUMBID",
    "FAILED_INVALID_FORMAT"
  ];
  transactionTeamActionTypes: [
    "INVOLVED",
    "ACCEPTED",
    "APPROVED",
    "VETOED",
    "PROTESTED"
  ];
  transactionTypes: [
    "TRADE_DECLINE",
    "TRADE_PROPOSAL",
    "TRADE_ACCEPT",
    "TRADE_UPHOLD",
    "TRADE_VETO",
    "WAIVER_ERROR",
    "TRADE_ERROR",
    "WAIVER",
    "ROSTER",
    "FUTURE_ROSTER",
    "RETRO_ROSTER",
    "FREEAGENT",
    "DRAFT"
  ];
  winnerTypes: ["HOME", "AWAY", "TIE", "UNDECIDED"];
}
